### PR TITLE
Wrap related items in 'record' tags

### PR DESCRIPTION
**Pull request by andylolz**
The register of members' financial interests uses lots of these:
```
<p class="spacer"><p>
```
…to separate different interest records. parlparse [currently ignores this information](https://github.com/mysociety/parlparse/blob/86451ea9/pyscraper/regmemfilter.py#L69), but it might be quite useful.

Note that this _does_ modify the structure of the output regmem xml.

### CODE REVIEW

**Comment by dracos** [comment]
I think it's fine, sorry I didn't get round to this before Christmas unlike the others :) Will hopefully take a look early next week.

**Comment by andylolz** [comment]
Ace – thanks!

**Comment by dracos** [comment]
Thanks, merged. The main issue now seems to be the strange treatment of subcategories with "(a)" etc appearing out of element, and the title of the subcategory appearing as a separate record. But that record behaviour is no worse than present, certainly!

**Comment by andylolz** [comment]
> It should be possible to go back and revise all of that data, but I don’t know how you feel about that idea…

Hi @dracos – just wondering about this. It looks like new xml generated by parlparse contains these records – that’s great! I was wondering if it’s likely this will also be retrospectively applied? i.e. revising the data held here:
http://www.theyworkforyou.com/pwdata/scrapedxml/regmem/

> The main issue now seems to be the strange treatment of subcategories with "(a)" etc appearing out of element, and the title of the subcategory appearing as a separate record.

Eek! I’ll look into these issues.

**Comment by dracos** [comment]
Probably, but I couldn't give you a date, sorry, probably want to sort out the version control issues first for one thing. I believe the register is going to be appearing on data.parliament.uk soon (Lords is already there), and if this includes historical information, then this might all be superfluous :)

**Pull request merged**
